---
- hosts: localhost
  connection: local
  gather_facts: false
  become: false

  vars:
    csvfile: "{{ lookup('file', 'template_input.csv') }}"

  tasks:

    - name: Parse CSV To YAML
      template:
        src: "./roles/{{ source }}/templates/main.j2"
        dest: "./roles/{{ source }}/vars/main.yml"
      run_once: true

    - name: Block of {{ source }} tasks
      block:
       - name: Call variables
         include_vars: ./roles/{{ source }}/vars/main.yml



       - name: Syntax checker - Tenant existence
         assert:
           that:
             - item.tenant is defined
           fail_msg: "Tenant not defined"
           success_msg: "Tenant defined"
         loop: "{{ epg }}"
         loop_control:
             pause: 1



       - name: Syntax checker - Tenant "common" existience
         assert:
           that:
             - item.tenant | regex_search('common')
           fail_msg: "Tenant common not defined"
           success_msg: "Tenant common defined"
         loop: "{{ epg }}"
         loop_control:
             pause: 1



       - name: Syntax checker - BD Subnet /24 existience
         assert:
           that:
             - item.bd | regex_search('\/24')
           fail_msg: "BD /24 not existient"
           success_msg: "BD /24 existient"
         loop: "{{ epg }}"
         loop_control:
             pause: 1



       - name: Syntax checker - App Profile name
         assert:
           that:
             - item.app_prof | regex_search('^ap\_.*')
           fail_msg: "App profile syntax not correct"
           success_msg: "App profile syntax correct"
         loop: "{{ epg }}"
         loop_control:
             pause: 1



       - name: Syntax checker - EPG Profile name
         assert:
           that:
             - item.name | regex_search('^epg\_.*')
           fail_msg: "EPG profile syntax not correct"
           success_msg: "EPG profile syntax correct"
         loop: "{{ epg }}"
         loop_control:
             pause: 1


       - name: Syntax checker - BD name
         assert:
           that:
             - item.bd | regex_search('^bd\_(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\/24')
           fail_msg: "BD profile syntax not correct"
           success_msg: "BD profile syntax correct"
         loop: "{{ epg }}"
         loop_control:
             pause: 1


      ignore_errors: true
      when: source == "epg"


